/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    application
    id("com.github.spotbugs") version "6.0.26" // Подключение SpotBugs
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-lang3:3.12.0")
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.assertj.assertj.core)
}

group = "ru.job4j"
version = "1.0"
description = "elementary"
java.sourceCompatibility = JavaVersion.VERSION_21

tasks.spotbugsMain {
    reports.create("html") {
        required = true
        outputLocation.set(layout.buildDirectory.file("reports/spotbugs/spotbugs.html"))
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks.test {
    finalizedBy(tasks.spotbugsMain)
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.register<Zip>("zipJavaDoc") {
    group = "documentation" // Группа, в которой будет отображаться задача
    description = "Packs the generated Javadoc into a zip archive"

    dependsOn("javadoc") // Указываем, что задача зависит от выполнения javadoc

    from("build/docs/javadoc") // Исходная папка для упаковки
    archiveFileName.set("javadoc.zip") // Имя создаваемого архива
    destinationDirectory.set(layout.buildDirectory.dir("archives")) // Директория, куда будет сохранен архив
}

tasks.register("checkJarSize") {
    group = "verification"
    description = "Checks the size of the generated JAR file."

    val jarFileProvider = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    dependsOn("jar")

    doLast {
        val jarFile = jarFileProvider.get().asFile
        val sizeInMB = jarFile.length().toDouble() / (1024.0 * 1024.0)

        if (!jarFile.exists()) {
            throw GradleException("JAR file not found: ${jarFile.absolutePath}")
        }

        if (sizeInMB > 5.0) {
            logger.warn("JAR file exceeds 5 MB. Current size: ${"%.2f".format(sizeInMB)} MB")
        } else {
            logger.lifecycle("JAR file is within limit. Current size: ${"%.2f".format(sizeInMB)} MB")
        }
    }
}
